baseURL = "https://www.jesustorres.es/"
defaultContentLanguage = "es"
languageCode = "es"
title = "Jesús Torres"
description = "Página personal y blog de Jesús Torres."
keywords = ["jmtorres", "Jesús Torres", "Universidad", "Linux", "Sistemas Operativos", "Qt", "C++"]

theme = "CodeIT"

# Actualizar el lastmod de cada página usando la fecha del commit
enableGitInfo = true

enableEmoji = true

[author]
  name = "Jesús Torres"
  email = "jmtorres@ull.es"
  link = "https://jesustorres.es/"

[params]
  version = "0.2.X"
  [params.page]
    # Mapbox GL JS config
    [params.page.mapbox]
      accessToken = "pk.eyJ1Ijoiam10b3JyZXMiLCJhIjoiY2tiZjhqZTB4MG44bzMwcDJxczlobTVncSJ9.7jnnoY0OkW-cw5WOYq0mag"
      lightStyle = "mapbox://styles/mapbox/light-v10"
      darkStyle = "mapbox://styles/mapbox/dark-v10"
      navigation = true
      geolocate = true
      scale = true
      fullscreen = true

    [params.page.share]
      enable = true
      Twitter = true
      Facebook = true
      Linkedin = true
      Telegram = true
      Whatsapp = true

  [params.header]
    [params.header.title]
      logo = ""
      name = "Jesús Torres"
      pre = '<i class="fas fa-code"></i>'
      post = ''

  [params.seo]
    image = "/thumbnail.png"
    thumbnailUrl = "/thumbnail.png"

  [params.footer]
    enable = true
    hugo = true
    copyright = true
    author = true
    since = 2013
    license = '<a rel="license" href="http://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a> — Excepto donde se indique lo contrario      '

  [params.home]
    [params.home.profile]
      enable = true
      # Avantar. Puede usarse Gravatar o cualquier imagen
      gravatarEmail = "jmtorres@ull.edu.es"
      #avatarURL = "/static/images/avatar.png"
      #subtitle = "Docente e investigador de la Universidad de La Laguna"
      # Use typeit animation for subtitle
      typeit = false
      social = true

    [params.home.posts]
      enable = true
      paginate = 6
  
  [params.page.comment]
    enable = false
    [params.page.comment.disqus]
      enable = true
      shortname = "jesus-torres"

  [params.social]
    GitHub = "aplatanado"
    Linkedin = "jesusmtorres"
    Twitter = "jesustorresdev"
    Youtubechannel = "UCvU1vw7r4hwgvfWVVtOW3Qg"
    Googlescholar = "-I2HnbIAAAAJ"
    Orcid = "0000-0003-4391-0170"
    Researchgate = "Jesus_Torres30"
    RSS = true

  [params.search]
    enable = true
    type = "lunr"
    snippetLength = 100

[frontmatter]
  date = ["date", "publishDate", ":filename", "lastmod"]
  publishDate = ["publishDate", "date", ":filename"]
  lastmod = ["lastmod", ":git", "date", "publishDate", ":filename"]

[taxonomies]
  #category = "categories"
  tag = "tags"
  series = "series"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Inicio"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    identifier = "tutorías"
    name = "Tutorías"
    url = "/tutorías/"
    weight = 2
  [[menu.main]]
    identifier = "linkedin"
    pre = "<i class='fab fa-linkedin fa-fw'></i>"
    post = ""
    name = ""
    url = "https://linkedin.com/in/jesusmtorres"
    title = "Linkedin"
    weight = 3

[markup]
  [markup.highlight]
    lineNumbersInTable = true
    # False is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false

[outputs]
  home = ["HTML", "RSS", "JSON"]

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5
